[
  {
    "faterMenu":"SQL",
    "faterLink":"http://www.jikexueyuan.com/course/sql/",
    "childMenu":[
      {
        "name":"MySQL",
        "link":"http://www.jikexueyuan.com/course/mysql/"
      },
      {
        "name":"SQL Server",
        "link":"http://www.jikexueyuan.com/course/sqlserver/"
      },
      {
        "name":"Oracle",
        "link":"http://www.jikexueyuan.com/course/oracledb/"
      },
      {
        "name":"SQLite",
        "link":"http://www.jikexueyuan.com/course/sqlite/"
      },
      {
        "name":"PostgreSQL",
        "link":"http://www.jikexueyuan.com/course/postgresql/"
      },
      {
        "name":"DB2",
        "link":"http://www.jikexueyuan.com/course/db2/"
      }
    ]
  },
  {
    "faterMenu":"NoSQL",
    "faterLink":"http://www.jikexueyuan.com/course/nosql/",
    "childMenu":[
      {
        "name":"Cassandra",
        "link":"http://www.jikexueyuan.com/course/cassandra/"
      },
      {
        "name":"Redis",
        "link":"http://www.jikexueyuan.com/course/redis/"
      },
      {
        "name":"MongoDB",
        "link":"http://www.jikexueyuan.com/course/mongoDB/"
      },
      {
        "name":"Unreal",
        "link":"http://www.jikexueyuan.com/course/unreal/"
      }
    ]
  },
  {
    "faterMenu":"游戏开发",
    "faterLink":"http://www.jikexueyuan.com/course/frame/",
    "childMenu":[
      {
        "name":"Cordova",
        "link":"http://www.jikexueyuan.com/course/cordova/"
      },
      {
        "name":"React Native",
        "link":"http://www.jikexueyuan.com/course/reactnative1/"
      }
    ]
  }
]

