[
  {
    "faterMenu":"应用开发",
    "faterLink":"http://www.jikexueyuan.com/course/app/",
    "childMenu":[
      {
        "name":"Android",
        "link":"http://www.jikexueyuan.com/course/android/"
      },
      {
        "name":"IOS",
        "link":"http://www.jikexueyuan.com/course/ios/"
      }
    ]
  },
  {
    "faterMenu":"游戏开发",
    "faterLink":"http://www.jikexueyuan.com/course/games/",
    "childMenu":[
      {
        "name":"Cocos",
        "link":"http://www.jikexueyuan.com/course/cocos/"
      },
      {
        "name":"Unity3D",
        "link":"http://www.jikexueyuan.com/course/unity3d/"
      },
      {
        "name":"SpriteKit 2D",
        "link":"http://www.jikexueyuan.com/course/spritekit2d/"
      },
      {
        "name":"Unreal",
        "link":"http://www.jikexueyuan.com/course/unreal/"
      }
    ]
  },
  {
    "faterMenu":"常用框架",
    "faterLink":"http://www.jikexueyuan.com/course/frame/",
    "childMenu":[
      {
        "name":"Cordova",
        "link":"http://www.jikexueyuan.com/course/cordova/"
      },
      {
        "name":"React Native",
        "link":"http://www.jikexueyuan.com/course/reactnative1/"
      }
    ]
  }
]

